//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_DOTNET_REST_PASPUEL_QUISTANCHALA_VILLARRUEL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int ID_MOVIMIENTO { get; set; }
        public int ID_CUENTA { get; set; }
        public Nullable<System.DateTime> FECHA_MOVIMIENTO { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public Nullable<decimal> IMPORTE_MOVIMIENTO { get; set; }
        public string DESTINO_MOVIMIENTO { get; set; }
        public Nullable<decimal> SALDO_MOVIMIENTO { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
    }
}
