//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombres_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidos_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cedula_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccion_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefono_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string correo_clienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((this.id_clienteField.Equals(value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombres_cliente {
            get {
                return this.nombres_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.nombres_clienteField, value) != true)) {
                    this.nombres_clienteField = value;
                    this.RaisePropertyChanged("nombres_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidos_cliente {
            get {
                return this.apellidos_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidos_clienteField, value) != true)) {
                    this.apellidos_clienteField = value;
                    this.RaisePropertyChanged("apellidos_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cedula_cliente {
            get {
                return this.cedula_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.cedula_clienteField, value) != true)) {
                    this.cedula_clienteField = value;
                    this.RaisePropertyChanged("cedula_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string direccion_cliente {
            get {
                return this.direccion_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.direccion_clienteField, value) != true)) {
                    this.direccion_clienteField = value;
                    this.RaisePropertyChanged("direccion_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string telefono_cliente {
            get {
                return this.telefono_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.telefono_clienteField, value) != true)) {
                    this.telefono_clienteField = value;
                    this.RaisePropertyChanged("telefono_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string correo_cliente {
            get {
                return this.correo_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.correo_clienteField, value) != true)) {
                    this.correo_clienteField = value;
                    this.RaisePropertyChanged("correo_cliente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_cuentaField;
        
        private int id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nro_cuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_cuentaField;
        
        private decimal saldo_cuentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_cuenta {
            get {
                return this.id_cuentaField;
            }
            set {
                if ((this.id_cuentaField.Equals(value) != true)) {
                    this.id_cuentaField = value;
                    this.RaisePropertyChanged("id_cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((this.id_clienteField.Equals(value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nro_cuenta {
            get {
                return this.nro_cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.nro_cuentaField, value) != true)) {
                    this.nro_cuentaField = value;
                    this.RaisePropertyChanged("nro_cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo_cuenta {
            get {
                return this.tipo_cuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_cuentaField, value) != true)) {
                    this.tipo_cuentaField = value;
                    this.RaisePropertyChanged("tipo_cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal saldo_cuenta {
            get {
                return this.saldo_cuentaField;
            }
            set {
                if ((this.saldo_cuentaField.Equals(value) != true)) {
                    this.saldo_cuentaField = value;
                    this.RaisePropertyChanged("saldo_cuenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_movimientoField;
        
        private int id_cuentaField;
        
        private System.DateTime fecha_movimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipo_movimientoField;
        
        private decimal importe_movimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destino_movimientoField;
        
        private decimal saldo_movimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_movimiento {
            get {
                return this.id_movimientoField;
            }
            set {
                if ((this.id_movimientoField.Equals(value) != true)) {
                    this.id_movimientoField = value;
                    this.RaisePropertyChanged("id_movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int id_cuenta {
            get {
                return this.id_cuentaField;
            }
            set {
                if ((this.id_cuentaField.Equals(value) != true)) {
                    this.id_cuentaField = value;
                    this.RaisePropertyChanged("id_cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime fecha_movimiento {
            get {
                return this.fecha_movimientoField;
            }
            set {
                if ((this.fecha_movimientoField.Equals(value) != true)) {
                    this.fecha_movimientoField = value;
                    this.RaisePropertyChanged("fecha_movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tipo_movimiento {
            get {
                return this.tipo_movimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipo_movimientoField, value) != true)) {
                    this.tipo_movimientoField = value;
                    this.RaisePropertyChanged("tipo_movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal importe_movimiento {
            get {
                return this.importe_movimientoField;
            }
            set {
                if ((this.importe_movimientoField.Equals(value) != true)) {
                    this.importe_movimientoField = value;
                    this.RaisePropertyChanged("importe_movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string destino_movimiento {
            get {
                return this.destino_movimientoField;
            }
            set {
                if ((object.ReferenceEquals(this.destino_movimientoField, value) != true)) {
                    this.destino_movimientoField = value;
                    this.RaisePropertyChanged("destino_movimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal saldo_movimiento {
            get {
                return this.saldo_movimientoField;
            }
            set {
                if ((this.saldo_movimientoField.Equals(value) != true)) {
                    this.saldo_movimientoField = value;
                    this.RaisePropertyChanged("saldo_movimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int id_usuarioField;
        
        private int id_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cedula_clienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombre_usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string password_usuarioField;
        
        private int cambio_usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id_usuario {
            get {
                return this.id_usuarioField;
            }
            set {
                if ((this.id_usuarioField.Equals(value) != true)) {
                    this.id_usuarioField = value;
                    this.RaisePropertyChanged("id_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int id_cliente {
            get {
                return this.id_clienteField;
            }
            set {
                if ((this.id_clienteField.Equals(value) != true)) {
                    this.id_clienteField = value;
                    this.RaisePropertyChanged("id_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cedula_cliente {
            get {
                return this.cedula_clienteField;
            }
            set {
                if ((object.ReferenceEquals(this.cedula_clienteField, value) != true)) {
                    this.cedula_clienteField = value;
                    this.RaisePropertyChanged("cedula_cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nombre_usuario {
            get {
                return this.nombre_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.nombre_usuarioField, value) != true)) {
                    this.nombre_usuarioField = value;
                    this.RaisePropertyChanged("nombre_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password_usuario {
            get {
                return this.password_usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.password_usuarioField, value) != true)) {
                    this.password_usuarioField = value;
                    this.RaisePropertyChanged("password_usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int cambio_usuario {
            get {
                return this.cambio_usuarioField;
            }
            set {
                if ((this.cambio_usuarioField.Equals(value) != true)) {
                    this.cambio_usuarioField = value;
                    this.RaisePropertyChanged("cambio_usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCoreBancario.WSCoreBancarioSoap")]
    public interface WSCoreBancarioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarCliente", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponse verificarCliente(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponse> verificarClienteAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuarioNombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inicioSesion", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponse inicioSesion(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/inicioSesion", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponse> inicioSesionAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cedula del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionConsolidada", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponse posicionConsolidada(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/posicionConsolidada", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponse> posicionConsolidadaAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/detalleMovimientos", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponse detalleMovimientos(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/detalleMovimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponse> detalleMovimientosAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuentaOrigen del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/transferencias", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponse transferencias(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/transferencias", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponse> transferenciasAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipoCuenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCuentaBancaria", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponse registrarCuentaBancaria(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCuentaBancaria", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponse> registrarCuentaBancariaAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreUsuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerUsuario", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponse obtenerUsuario(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponse> obtenerUsuarioAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreUsuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarContrasena", ReplyAction="*")]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponse actualizarContrasena(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/actualizarContrasena", ReplyAction="*")]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponse> actualizarContrasenaAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificarCliente", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequestBody Body;
        
        public verificarClienteRequest() {
        }
        
        public verificarClienteRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cuenta;
        
        public verificarClienteRequestBody() {
        }
        
        public verificarClienteRequestBody(string cedula, string cuenta) {
            this.cedula = cedula;
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class verificarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="verificarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponseBody Body;
        
        public verificarClienteResponse() {
        }
        
        public verificarClienteResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class verificarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Cliente verificarClienteResult;
        
        public verificarClienteResponseBody() {
        }
        
        public verificarClienteResponseBody(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Cliente verificarClienteResult) {
            this.verificarClienteResult = verificarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inicioSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="inicioSesion", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequestBody Body;
        
        public inicioSesionRequest() {
        }
        
        public inicioSesionRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class inicioSesionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasena;
        
        public inicioSesionRequestBody() {
        }
        
        public inicioSesionRequestBody(string usuarioNombre, string contrasena) {
            this.usuarioNombre = usuarioNombre;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class inicioSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="inicioSesionResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponseBody Body;
        
        public inicioSesionResponse() {
        }
        
        public inicioSesionResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class inicioSesionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool inicioSesionResult;
        
        public inicioSesionResponseBody() {
        }
        
        public inicioSesionResponseBody(bool inicioSesionResult) {
            this.inicioSesionResult = inicioSesionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class posicionConsolidadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="posicionConsolidada", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequestBody Body;
        
        public posicionConsolidadaRequest() {
        }
        
        public posicionConsolidadaRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class posicionConsolidadaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cedula;
        
        public posicionConsolidadaRequestBody() {
        }
        
        public posicionConsolidadaRequestBody(string cedula) {
            this.cedula = cedula;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class posicionConsolidadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="posicionConsolidadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponseBody Body;
        
        public posicionConsolidadaResponse() {
        }
        
        public posicionConsolidadaResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class posicionConsolidadaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Cuenta> posicionConsolidadaResult;
        
        public posicionConsolidadaResponseBody() {
        }
        
        public posicionConsolidadaResponseBody(System.Collections.Generic.List<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Cuenta> posicionConsolidadaResult) {
            this.posicionConsolidadaResult = posicionConsolidadaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class detalleMovimientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="detalleMovimientos", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequestBody Body;
        
        public detalleMovimientosRequest() {
        }
        
        public detalleMovimientosRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class detalleMovimientosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public detalleMovimientosRequestBody() {
        }
        
        public detalleMovimientosRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class detalleMovimientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="detalleMovimientosResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponseBody Body;
        
        public detalleMovimientosResponse() {
        }
        
        public detalleMovimientosResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class detalleMovimientosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Movimiento> detalleMovimientosResult;
        
        public detalleMovimientosResponseBody() {
        }
        
        public detalleMovimientosResponseBody(System.Collections.Generic.List<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Movimiento> detalleMovimientosResult) {
            this.detalleMovimientosResult = detalleMovimientosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferenciasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transferencias", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequestBody Body;
        
        public transferenciasRequest() {
        }
        
        public transferenciasRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class transferenciasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double importe;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cuentaDestino;
        
        public transferenciasRequestBody() {
        }
        
        public transferenciasRequestBody(string cuentaOrigen, double importe, string cuentaDestino) {
            this.cuentaOrigen = cuentaOrigen;
            this.importe = importe;
            this.cuentaDestino = cuentaDestino;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class transferenciasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="transferenciasResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponseBody Body;
        
        public transferenciasResponse() {
        }
        
        public transferenciasResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class transferenciasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool transferenciasResult;
        
        public transferenciasResponseBody() {
        }
        
        public transferenciasResponseBody(bool transferenciasResult) {
            this.transferenciasResult = transferenciasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCuentaBancariaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCuentaBancaria", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequestBody Body;
        
        public registrarCuentaBancariaRequest() {
        }
        
        public registrarCuentaBancariaRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCuentaBancariaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string tipoCuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double saldoInicial;
        
        public registrarCuentaBancariaRequestBody() {
        }
        
        public registrarCuentaBancariaRequestBody(int idCliente, string tipoCuenta, double saldoInicial) {
            this.idCliente = idCliente;
            this.tipoCuenta = tipoCuenta;
            this.saldoInicial = saldoInicial;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCuentaBancariaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCuentaBancariaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponseBody Body;
        
        public registrarCuentaBancariaResponse() {
        }
        
        public registrarCuentaBancariaResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCuentaBancariaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool registrarCuentaBancariaResult;
        
        public registrarCuentaBancariaResponseBody() {
        }
        
        public registrarCuentaBancariaResponseBody(bool registrarCuentaBancariaResult) {
            this.registrarCuentaBancariaResult = registrarCuentaBancariaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerUsuario", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequestBody Body;
        
        public obtenerUsuarioRequest() {
        }
        
        public obtenerUsuarioRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreUsuario;
        
        public obtenerUsuarioRequestBody() {
        }
        
        public obtenerUsuarioRequestBody(string nombreUsuario) {
            this.nombreUsuario = nombreUsuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponseBody Body;
        
        public obtenerUsuarioResponse() {
        }
        
        public obtenerUsuarioResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Usuario obtenerUsuarioResult;
        
        public obtenerUsuarioResponseBody() {
        }
        
        public obtenerUsuarioResponseBody(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Usuario obtenerUsuarioResult) {
            this.obtenerUsuarioResult = obtenerUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarContrasenaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarContrasena", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequestBody Body;
        
        public actualizarContrasenaRequest() {
        }
        
        public actualizarContrasenaRequest(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarContrasenaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string contrasenia;
        
        public actualizarContrasenaRequestBody() {
        }
        
        public actualizarContrasenaRequestBody(string nombreUsuario, string contrasenia) {
            this.nombreUsuario = nombreUsuario;
            this.contrasenia = contrasenia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class actualizarContrasenaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="actualizarContrasenaResponse", Namespace="http://tempuri.org/", Order=0)]
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponseBody Body;
        
        public actualizarContrasenaResponse() {
        }
        
        public actualizarContrasenaResponse(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class actualizarContrasenaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool actualizarContrasenaResult;
        
        public actualizarContrasenaResponseBody() {
        }
        
        public actualizarContrasenaResponseBody(bool actualizarContrasenaResult) {
            this.actualizarContrasenaResult = actualizarContrasenaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCoreBancarioSoapChannel : PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCoreBancarioSoapClient : System.ServiceModel.ClientBase<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap>, PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap {
        
        public WSCoreBancarioSoapClient() {
        }
        
        public WSCoreBancarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCoreBancarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCoreBancarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCoreBancarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.verificarCliente(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest request) {
            return base.Channel.verificarCliente(request);
        }
        
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Cliente verificarCliente(string cedula, string cuenta) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.cuenta = cuenta;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).verificarCliente(inValue);
            return retVal.Body.verificarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.verificarClienteAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest request) {
            return base.Channel.verificarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteResponse> verificarClienteAsync(string cedula, string cuenta) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.verificarClienteRequestBody();
            inValue.Body.cedula = cedula;
            inValue.Body.cuenta = cuenta;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).verificarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.inicioSesion(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest request) {
            return base.Channel.inicioSesion(request);
        }
        
        public bool inicioSesion(string usuarioNombre, string contrasena) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequestBody();
            inValue.Body.usuarioNombre = usuarioNombre;
            inValue.Body.contrasena = contrasena;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).inicioSesion(inValue);
            return retVal.Body.inicioSesionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.inicioSesionAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest request) {
            return base.Channel.inicioSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionResponse> inicioSesionAsync(string usuarioNombre, string contrasena) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.inicioSesionRequestBody();
            inValue.Body.usuarioNombre = usuarioNombre;
            inValue.Body.contrasena = contrasena;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).inicioSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.posicionConsolidada(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest request) {
            return base.Channel.posicionConsolidada(request);
        }
        
        public System.Collections.Generic.List<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Cuenta> posicionConsolidada(string cedula) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequestBody();
            inValue.Body.cedula = cedula;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).posicionConsolidada(inValue);
            return retVal.Body.posicionConsolidadaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.posicionConsolidadaAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest request) {
            return base.Channel.posicionConsolidadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaResponse> posicionConsolidadaAsync(string cedula) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.posicionConsolidadaRequestBody();
            inValue.Body.cedula = cedula;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).posicionConsolidadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.detalleMovimientos(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest request) {
            return base.Channel.detalleMovimientos(request);
        }
        
        public System.Collections.Generic.List<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Movimiento> detalleMovimientos(string cuenta) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequestBody();
            inValue.Body.cuenta = cuenta;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).detalleMovimientos(inValue);
            return retVal.Body.detalleMovimientosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.detalleMovimientosAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest request) {
            return base.Channel.detalleMovimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosResponse> detalleMovimientosAsync(string cuenta) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.detalleMovimientosRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).detalleMovimientosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.transferencias(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest request) {
            return base.Channel.transferencias(request);
        }
        
        public bool transferencias(string cuentaOrigen, double importe, string cuentaDestino) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequestBody();
            inValue.Body.cuentaOrigen = cuentaOrigen;
            inValue.Body.importe = importe;
            inValue.Body.cuentaDestino = cuentaDestino;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).transferencias(inValue);
            return retVal.Body.transferenciasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.transferenciasAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest request) {
            return base.Channel.transferenciasAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasResponse> transferenciasAsync(string cuentaOrigen, double importe, string cuentaDestino) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.transferenciasRequestBody();
            inValue.Body.cuentaOrigen = cuentaOrigen;
            inValue.Body.importe = importe;
            inValue.Body.cuentaDestino = cuentaDestino;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).transferenciasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.registrarCuentaBancaria(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest request) {
            return base.Channel.registrarCuentaBancaria(request);
        }
        
        public bool registrarCuentaBancaria(int idCliente, string tipoCuenta, double saldoInicial) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.tipoCuenta = tipoCuenta;
            inValue.Body.saldoInicial = saldoInicial;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).registrarCuentaBancaria(inValue);
            return retVal.Body.registrarCuentaBancariaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.registrarCuentaBancariaAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest request) {
            return base.Channel.registrarCuentaBancariaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaResponse> registrarCuentaBancariaAsync(int idCliente, string tipoCuenta, double saldoInicial) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.registrarCuentaBancariaRequestBody();
            inValue.Body.idCliente = idCliente;
            inValue.Body.tipoCuenta = tipoCuenta;
            inValue.Body.saldoInicial = saldoInicial;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).registrarCuentaBancariaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.obtenerUsuario(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest request) {
            return base.Channel.obtenerUsuario(request);
        }
        
        public PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.Usuario obtenerUsuario(string nombreUsuario) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).obtenerUsuario(inValue);
            return retVal.Body.obtenerUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.obtenerUsuarioAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest request) {
            return base.Channel.obtenerUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioResponse> obtenerUsuarioAsync(string nombreUsuario) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.obtenerUsuarioRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).obtenerUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponse PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.actualizarContrasena(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest request) {
            return base.Channel.actualizarContrasena(request);
        }
        
        public bool actualizarContrasena(string nombreUsuario, string contrasenia) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.contrasenia = contrasenia;
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponse retVal = ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).actualizarContrasena(inValue);
            return retVal.Body.actualizarContrasenaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponse> PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap.actualizarContrasenaAsync(PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest request) {
            return base.Channel.actualizarContrasenaAsync(request);
        }
        
        public System.Threading.Tasks.Task<PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaResponse> actualizarContrasenaAsync(string nombreUsuario, string contrasenia) {
            PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest inValue = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequest();
            inValue.Body = new PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.actualizarContrasenaRequestBody();
            inValue.Body.nombreUsuario = nombreUsuario;
            inValue.Body.contrasenia = contrasenia;
            return ((PROYECTO_DOTNET_SOAP_CLIENTE_PASPUEL_QUISTANCHALA_VILLARRUEL.WSCoreBancario.WSCoreBancarioSoap)(this)).actualizarContrasenaAsync(inValue);
        }
    }
}
