//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_DOTNET_SOAP_PASPUEL_QUISTANCHALA_VILLARRUEL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIMIENTO
    {
        public int ID_MOVIMIENTO { get; set; }
        public int ID_CUENTA { get; set; }
        public Nullable<System.DateTime> FECHA_MOVIMIENTO { get; set; }
        public string TIPO_MOVIMIENTO { get; set; }
        public Nullable<decimal> IMPORTE_MOVIMIENTO { get; set; }
        public string DESTINO_MOVIMIENTO { get; set; }
        public Nullable<decimal> SALDO_MOVIMIENTO { get; set; }
    
        public virtual CUENTA CUENTA { get; set; }
    }
}
