//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_DOTNET_SOAP_PASPUEL_QUISTANCHALA_VILLARRUEL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public Nullable<int> ID_CLIENTE { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string PASSWORD_USUARIO { get; set; }
        public Nullable<int> CAMBIO_USUARIO { get; set; }
    }
}
